#!/bin/bash
exec 2>&1
echo "Seeding Mongo Collection"
MONGODB_HOME=$(hab pkg path learn/mongodb)

{{~#if bind.database}}
{{~#each bind.database.members}}

  export MONGOIMPORT_OPTS="--host={{sys.ip}} --port={{cfg.port}}"

{{~/each}}
{{~/if}}

echo "\$MONGOIMPORT_OPTS=$MONGOIMPORT_OPTS"

$(hab pkg path core/mongo-tools)/bin/mongoimport --drop -d demo -c nationalparks --type json --jsonArray --file {{pkg.path}}/national-parks.json ${MONGOIMPORT_OPTS}



