#!/bin/bash
exec 2>&1
echo "Seeding Mongo Collection"

{{#if bind.has_database}}
{{~#each bind.database.members as |member|}}
{{~#if member.alive}}

  export MONGOIMPORT_OPTS="--host={{member.sys.ip}} --port={{member.cfg.port}}"
{{~/if}}
{{~/each}}
{{~/if}}

echo "\$MONGOIMPORT_OPTS=$MONGOIMPORT_OPTS"

$(hab pkg path core/mongo-tools)/bin/mongoimport --drop -d demo -c nationalparks --type json --jsonArray --file {{pkg.path}}/national-parks.json ${MONGOIMPORT_OPTS}



