#!/bin/bash
exec 2>&1
echo "Starting Apache Tomcat"

export JAVA_HOME=$(hab pkg path core/jdk8)
export TOMCAT_HOME="$(hab pkg path core/tomcat8)/tc"

{{#if bind.has_database}}
{{~#each bind.database.members as |member|}}
{{~#if member.alive}}
  export CATALINA_OPTS="-DMONGODB_SERVICE_HOST={{member.sys.ip}} -DMONGODB_SERVICE_PORT={{member.cfg.port}}
{{~/if}}
{{~/each}}
{{~/if}}

echo "\$CATALINA_OPTS=$CATALINA_OPTS"

cp "$(hab pkg path {{pkg.origin}}/{{pkg.name}})/{{pkg.name}}.war" "$TOMCAT_HOME/webapps/"

exec ${TOMCAT_HOME}/bin/catalina.sh run

